# Hardware Features
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
EXTRAKEY_ENABLE = yes

LTO_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes

COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
